version: "3.8"

services:
  python-worker:
    build: ./microservices/python-worker-1
    container_name: python-worker
    ports:
      - "5000:5000"

  node-api:
    build: ./microservices/node-api-1
    container_name: node-api
    environment:
      - PYTHON_SERVICE=python-worker:5000
    ports:
      - "3000:3000"

  go-gateway:
    build: ./microservices/go-gateway-1
    container_name: go-gateway
    environment:
      - NODE_SERVICE=node-api:3000
    ports:
      - "8086:8086"
